export const Recent = [
  "😆",
  "😃",
  "😄",
  "😁",
  "😆",
  "👿",
  "🥵",
  "🥶",
  "💯",
  "❤️",
  "🐸",
  "🐹",
  "🍪",
  "💀",
  "📞",
  "☠️",
  "🎤",
  "🔨",
];
export const Category = [
  "Smileys & Emotion",
  "People & Body",
  "Animals & Nature",
  "Food & Drink",
  "Travel & Places",
  "Activities",
  "Objects",
  "Symbols",
];
export const GroupCat = [
  { cordonate: 0, title: "⏰" },
  { cordonate: 125, title: "😀" },
  { cordonate: 855, title: "👶" },
  { cordonate: 2410, title: "🐵" },
  { cordonate: 3060, title: "🍇" },
  { cordonate: 3665, title: "🌍" },
  { cordonate: 4655, title: "🎃" },
  { cordonate: 5090, title: "👓" },
  { cordonate: 6215, title: "🏧" },
];
